services:

  postgres:
    image: postgres:16
    env_file:
      - postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3.12-management
    env_file:
      - rabbitmq.env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"


volumes:
  postgres_data:
  rabbitmq_data: